# Generated by Django 4.2.4 on 2023-10-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
