# Generated by Django 4.2.4 on 2023-10-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0003_rename_lastincome_money_lasttransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
